language: python
sudo: false
python:
- 2.7
- 3.4
- 3.5
- 3.6
install:
- |
  if [ "$TEST_TYPE" = build ]; then
    pip install -e .[test]
    pip install mock
    pip install psycopg2 # Required for Django postgres fields testing
    pip install django==$DJANGO_VERSION
    python setup.py develop
  elif [ "$TEST_TYPE" = lint ]; then
    pip install flake8
  fi
script:
- |
  if [ "$TEST_TYPE" = lint ]; then
    echo "Checking Python code lint."
    flake8 graphene_django_authorization
    exit
  elif [ "$TEST_TYPE" = build ]; then
    py.test --cov=graphene_django_authorization examples
  fi
after_success:
- |
  if [ "$TEST_TYPE" = build ]; then
      coveralls
  fi
env:
  matrix:
  - TEST_TYPE=build DJANGO_VERSION=1.11
matrix:
  fast_finish: true
  include:
  - python: '2.7'
    env: TEST_TYPE=build DJANGO_VERSION=1.8
  - python: '2.7'
    env: TEST_TYPE=build DJANGO_VERSION=1.9
  - python: '2.7'
    env: TEST_TYPE=build DJANGO_VERSION=1.10
  - python: '2.7'
    env: TEST_TYPE=lint
